// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAgentSession(db *gorm.DB, opts ...gen.DOOption) agentSession {
	_agentSession := agentSession{}

	_agentSession.agentSessionDo.UseDB(db, opts...)
	_agentSession.agentSessionDo.UseModel(&models.AgentSession{})

	tableName := _agentSession.agentSessionDo.TableName()
	_agentSession.ALL = field.NewAsterisk(tableName)
	_agentSession.ID = field.NewUint64(tableName, "id")
	_agentSession.CreatedAt = field.NewTime(tableName, "created_at")
	_agentSession.UpdatedAt = field.NewTime(tableName, "updated_at")
	_agentSession.CreatedBy = field.NewUint64(tableName, "created_by")
	_agentSession.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_agentSession.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_agentSession.Remark = field.NewString(tableName, "remark")
	_agentSession.DeletedAt = field.NewUint(tableName, "deleted_at")
	_agentSession.SessionID = field.NewString(tableName, "session_id")
	_agentSession.Title = field.NewString(tableName, "title")
	_agentSession.Status = field.NewString(tableName, "status")
	_agentSession.Metadata = field.NewField(tableName, "metadata")

	_agentSession.fillFieldMap()

	return _agentSession
}

type agentSession struct {
	agentSessionDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	CreatedBy field.Uint64
	UpdatedBy field.Uint64
	DeletedBy field.Uint64
	Remark    field.String
	DeletedAt field.Uint
	SessionID field.String // 会话唯一标识
	Title     field.String // 会话标题
	Status    field.String // 会话状态 active/archived
	Metadata  field.Field  // 扩展元数据

	fieldMap map[string]field.Expr
}

func (a agentSession) Table(newTableName string) *agentSession {
	a.agentSessionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentSession) As(alias string) *agentSession {
	a.agentSessionDo.DO = *(a.agentSessionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentSession) updateTableName(table string) *agentSession {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.CreatedBy = field.NewUint64(table, "created_by")
	a.UpdatedBy = field.NewUint64(table, "updated_by")
	a.DeletedBy = field.NewUint64(table, "deleted_by")
	a.Remark = field.NewString(table, "remark")
	a.DeletedAt = field.NewUint(table, "deleted_at")
	a.SessionID = field.NewString(table, "session_id")
	a.Title = field.NewString(table, "title")
	a.Status = field.NewString(table, "status")
	a.Metadata = field.NewField(table, "metadata")

	a.fillFieldMap()

	return a
}

func (a *agentSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentSession) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["created_by"] = a.CreatedBy
	a.fieldMap["updated_by"] = a.UpdatedBy
	a.fieldMap["deleted_by"] = a.DeletedBy
	a.fieldMap["remark"] = a.Remark
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["title"] = a.Title
	a.fieldMap["status"] = a.Status
	a.fieldMap["metadata"] = a.Metadata
}

func (a agentSession) clone(db *gorm.DB) agentSession {
	a.agentSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentSession) replaceDB(db *gorm.DB) agentSession {
	a.agentSessionDo.ReplaceDB(db)
	return a
}

type agentSessionDo struct{ gen.DO }

type IAgentSessionDo interface {
	gen.SubQuery
	Debug() IAgentSessionDo
	WithContext(ctx context.Context) IAgentSessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentSessionDo
	WriteDB() IAgentSessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentSessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentSessionDo
	Not(conds ...gen.Condition) IAgentSessionDo
	Or(conds ...gen.Condition) IAgentSessionDo
	Select(conds ...field.Expr) IAgentSessionDo
	Where(conds ...gen.Condition) IAgentSessionDo
	Order(conds ...field.Expr) IAgentSessionDo
	Distinct(cols ...field.Expr) IAgentSessionDo
	Omit(cols ...field.Expr) IAgentSessionDo
	Join(table schema.Tabler, on ...field.Expr) IAgentSessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentSessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentSessionDo
	Group(cols ...field.Expr) IAgentSessionDo
	Having(conds ...gen.Condition) IAgentSessionDo
	Limit(limit int) IAgentSessionDo
	Offset(offset int) IAgentSessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentSessionDo
	Unscoped() IAgentSessionDo
	Create(values ...*models.AgentSession) error
	CreateInBatches(values []*models.AgentSession, batchSize int) error
	Save(values ...*models.AgentSession) error
	First() (*models.AgentSession, error)
	Take() (*models.AgentSession, error)
	Last() (*models.AgentSession, error)
	Find() ([]*models.AgentSession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentSession, err error)
	FindInBatches(result *[]*models.AgentSession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentSession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentSessionDo
	Assign(attrs ...field.AssignExpr) IAgentSessionDo
	Joins(fields ...field.RelationField) IAgentSessionDo
	Preload(fields ...field.RelationField) IAgentSessionDo
	FirstOrInit() (*models.AgentSession, error)
	FirstOrCreate() (*models.AgentSession, error)
	FindByPage(offset int, limit int) (result []*models.AgentSession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentSessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentSessionDo) Debug() IAgentSessionDo {
	return a.withDO(a.DO.Debug())
}

func (a agentSessionDo) WithContext(ctx context.Context) IAgentSessionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentSessionDo) ReadDB() IAgentSessionDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentSessionDo) WriteDB() IAgentSessionDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentSessionDo) Session(config *gorm.Session) IAgentSessionDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentSessionDo) Clauses(conds ...clause.Expression) IAgentSessionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentSessionDo) Returning(value interface{}, columns ...string) IAgentSessionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentSessionDo) Not(conds ...gen.Condition) IAgentSessionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentSessionDo) Or(conds ...gen.Condition) IAgentSessionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentSessionDo) Select(conds ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentSessionDo) Where(conds ...gen.Condition) IAgentSessionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentSessionDo) Order(conds ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentSessionDo) Distinct(cols ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentSessionDo) Omit(cols ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentSessionDo) Join(table schema.Tabler, on ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentSessionDo) Group(cols ...field.Expr) IAgentSessionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentSessionDo) Having(conds ...gen.Condition) IAgentSessionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentSessionDo) Limit(limit int) IAgentSessionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentSessionDo) Offset(offset int) IAgentSessionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentSessionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentSessionDo) Unscoped() IAgentSessionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentSessionDo) Create(values ...*models.AgentSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentSessionDo) CreateInBatches(values []*models.AgentSession, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentSessionDo) Save(values ...*models.AgentSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentSessionDo) First() (*models.AgentSession, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentSession), nil
	}
}

func (a agentSessionDo) Take() (*models.AgentSession, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentSession), nil
	}
}

func (a agentSessionDo) Last() (*models.AgentSession, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentSession), nil
	}
}

func (a agentSessionDo) Find() ([]*models.AgentSession, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentSession), err
}

func (a agentSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentSession, err error) {
	buf := make([]*models.AgentSession, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentSessionDo) FindInBatches(result *[]*models.AgentSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentSessionDo) Attrs(attrs ...field.AssignExpr) IAgentSessionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentSessionDo) Assign(attrs ...field.AssignExpr) IAgentSessionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentSessionDo) Joins(fields ...field.RelationField) IAgentSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentSessionDo) Preload(fields ...field.RelationField) IAgentSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentSessionDo) FirstOrInit() (*models.AgentSession, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentSession), nil
	}
}

func (a agentSessionDo) FirstOrCreate() (*models.AgentSession, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentSession), nil
	}
}

func (a agentSessionDo) FindByPage(offset int, limit int) (result []*models.AgentSession, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentSessionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentSessionDo) Delete(models ...*models.AgentSession) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentSessionDo) withDO(do gen.Dao) *agentSessionDo {
	a.DO = *do.(*gen.DO)
	return a
}
