// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAgentMessage(db *gorm.DB, opts ...gen.DOOption) agentMessage {
	_agentMessage := agentMessage{}

	_agentMessage.agentMessageDo.UseDB(db, opts...)
	_agentMessage.agentMessageDo.UseModel(&models.AgentMessage{})

	tableName := _agentMessage.agentMessageDo.TableName()
	_agentMessage.ALL = field.NewAsterisk(tableName)
	_agentMessage.ID = field.NewUint64(tableName, "id")
	_agentMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_agentMessage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_agentMessage.CreatedBy = field.NewUint64(tableName, "created_by")
	_agentMessage.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_agentMessage.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_agentMessage.DeletedAt = field.NewUint(tableName, "deleted_at")
	_agentMessage.SessionID = field.NewUint64(tableName, "session_id")
	_agentMessage.Role = field.NewString(tableName, "role")
	_agentMessage.Content = field.NewString(tableName, "content")
	_agentMessage.TokenCount = field.NewInt(tableName, "token_count")
	_agentMessage.Metadata = field.NewField(tableName, "metadata")
	_agentMessage.Session = agentMessageHasOneSession{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Session", "models.AgentSession"),
	}

	_agentMessage.fillFieldMap()

	return _agentMessage
}

type agentMessage struct {
	agentMessageDo

	ALL        field.Asterisk
	ID         field.Uint64
	CreatedAt  field.Time
	UpdatedAt  field.Time
	CreatedBy  field.Uint64
	UpdatedBy  field.Uint64
	DeletedBy  field.Uint64
	DeletedAt  field.Uint
	SessionID  field.Uint64 // 所属会话ID
	Role       field.String // 角色 user/assistant/system/tool
	Content    field.String // 消息内容
	TokenCount field.Int    // Token 数量
	Metadata   field.Field  // 扩展元数据
	Session    agentMessageHasOneSession

	fieldMap map[string]field.Expr
}

func (a agentMessage) Table(newTableName string) *agentMessage {
	a.agentMessageDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentMessage) As(alias string) *agentMessage {
	a.agentMessageDo.DO = *(a.agentMessageDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentMessage) updateTableName(table string) *agentMessage {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.CreatedBy = field.NewUint64(table, "created_by")
	a.UpdatedBy = field.NewUint64(table, "updated_by")
	a.DeletedBy = field.NewUint64(table, "deleted_by")
	a.DeletedAt = field.NewUint(table, "deleted_at")
	a.SessionID = field.NewUint64(table, "session_id")
	a.Role = field.NewString(table, "role")
	a.Content = field.NewString(table, "content")
	a.TokenCount = field.NewInt(table, "token_count")
	a.Metadata = field.NewField(table, "metadata")

	a.fillFieldMap()

	return a
}

func (a *agentMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentMessage) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["created_by"] = a.CreatedBy
	a.fieldMap["updated_by"] = a.UpdatedBy
	a.fieldMap["deleted_by"] = a.DeletedBy
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["session_id"] = a.SessionID
	a.fieldMap["role"] = a.Role
	a.fieldMap["content"] = a.Content
	a.fieldMap["token_count"] = a.TokenCount
	a.fieldMap["metadata"] = a.Metadata

}

func (a agentMessage) clone(db *gorm.DB) agentMessage {
	a.agentMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	a.Session.db = db.Session(&gorm.Session{Initialized: true})
	a.Session.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a agentMessage) replaceDB(db *gorm.DB) agentMessage {
	a.agentMessageDo.ReplaceDB(db)
	a.Session.db = db.Session(&gorm.Session{})
	return a
}

type agentMessageHasOneSession struct {
	db *gorm.DB

	field.RelationField
}

func (a agentMessageHasOneSession) Where(conds ...field.Expr) *agentMessageHasOneSession {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a agentMessageHasOneSession) WithContext(ctx context.Context) *agentMessageHasOneSession {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a agentMessageHasOneSession) Session(session *gorm.Session) *agentMessageHasOneSession {
	a.db = a.db.Session(session)
	return &a
}

func (a agentMessageHasOneSession) Model(m *models.AgentMessage) *agentMessageHasOneSessionTx {
	return &agentMessageHasOneSessionTx{a.db.Model(m).Association(a.Name())}
}

func (a agentMessageHasOneSession) Unscoped() *agentMessageHasOneSession {
	a.db = a.db.Unscoped()
	return &a
}

type agentMessageHasOneSessionTx struct{ tx *gorm.Association }

func (a agentMessageHasOneSessionTx) Find() (result *models.AgentSession, err error) {
	return result, a.tx.Find(&result)
}

func (a agentMessageHasOneSessionTx) Append(values ...*models.AgentSession) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a agentMessageHasOneSessionTx) Replace(values ...*models.AgentSession) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a agentMessageHasOneSessionTx) Delete(values ...*models.AgentSession) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a agentMessageHasOneSessionTx) Clear() error {
	return a.tx.Clear()
}

func (a agentMessageHasOneSessionTx) Count() int64 {
	return a.tx.Count()
}

func (a agentMessageHasOneSessionTx) Unscoped() *agentMessageHasOneSessionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type agentMessageDo struct{ gen.DO }

type IAgentMessageDo interface {
	gen.SubQuery
	Debug() IAgentMessageDo
	WithContext(ctx context.Context) IAgentMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentMessageDo
	WriteDB() IAgentMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentMessageDo
	Not(conds ...gen.Condition) IAgentMessageDo
	Or(conds ...gen.Condition) IAgentMessageDo
	Select(conds ...field.Expr) IAgentMessageDo
	Where(conds ...gen.Condition) IAgentMessageDo
	Order(conds ...field.Expr) IAgentMessageDo
	Distinct(cols ...field.Expr) IAgentMessageDo
	Omit(cols ...field.Expr) IAgentMessageDo
	Join(table schema.Tabler, on ...field.Expr) IAgentMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentMessageDo
	Group(cols ...field.Expr) IAgentMessageDo
	Having(conds ...gen.Condition) IAgentMessageDo
	Limit(limit int) IAgentMessageDo
	Offset(offset int) IAgentMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentMessageDo
	Unscoped() IAgentMessageDo
	Create(values ...*models.AgentMessage) error
	CreateInBatches(values []*models.AgentMessage, batchSize int) error
	Save(values ...*models.AgentMessage) error
	First() (*models.AgentMessage, error)
	Take() (*models.AgentMessage, error)
	Last() (*models.AgentMessage, error)
	Find() ([]*models.AgentMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentMessage, err error)
	FindInBatches(result *[]*models.AgentMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentMessageDo
	Assign(attrs ...field.AssignExpr) IAgentMessageDo
	Joins(fields ...field.RelationField) IAgentMessageDo
	Preload(fields ...field.RelationField) IAgentMessageDo
	FirstOrInit() (*models.AgentMessage, error)
	FirstOrCreate() (*models.AgentMessage, error)
	FindByPage(offset int, limit int) (result []*models.AgentMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentMessageDo) Debug() IAgentMessageDo {
	return a.withDO(a.DO.Debug())
}

func (a agentMessageDo) WithContext(ctx context.Context) IAgentMessageDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentMessageDo) ReadDB() IAgentMessageDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentMessageDo) WriteDB() IAgentMessageDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentMessageDo) Session(config *gorm.Session) IAgentMessageDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentMessageDo) Clauses(conds ...clause.Expression) IAgentMessageDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentMessageDo) Returning(value interface{}, columns ...string) IAgentMessageDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentMessageDo) Not(conds ...gen.Condition) IAgentMessageDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentMessageDo) Or(conds ...gen.Condition) IAgentMessageDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentMessageDo) Select(conds ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentMessageDo) Where(conds ...gen.Condition) IAgentMessageDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentMessageDo) Order(conds ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentMessageDo) Distinct(cols ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentMessageDo) Omit(cols ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentMessageDo) Join(table schema.Tabler, on ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentMessageDo) Group(cols ...field.Expr) IAgentMessageDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentMessageDo) Having(conds ...gen.Condition) IAgentMessageDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentMessageDo) Limit(limit int) IAgentMessageDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentMessageDo) Offset(offset int) IAgentMessageDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentMessageDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentMessageDo) Unscoped() IAgentMessageDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentMessageDo) Create(values ...*models.AgentMessage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentMessageDo) CreateInBatches(values []*models.AgentMessage, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentMessageDo) Save(values ...*models.AgentMessage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentMessageDo) First() (*models.AgentMessage, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentMessage), nil
	}
}

func (a agentMessageDo) Take() (*models.AgentMessage, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentMessage), nil
	}
}

func (a agentMessageDo) Last() (*models.AgentMessage, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentMessage), nil
	}
}

func (a agentMessageDo) Find() ([]*models.AgentMessage, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentMessage), err
}

func (a agentMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentMessage, err error) {
	buf := make([]*models.AgentMessage, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentMessageDo) FindInBatches(result *[]*models.AgentMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentMessageDo) Attrs(attrs ...field.AssignExpr) IAgentMessageDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentMessageDo) Assign(attrs ...field.AssignExpr) IAgentMessageDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentMessageDo) Joins(fields ...field.RelationField) IAgentMessageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentMessageDo) Preload(fields ...field.RelationField) IAgentMessageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentMessageDo) FirstOrInit() (*models.AgentMessage, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentMessage), nil
	}
}

func (a agentMessageDo) FirstOrCreate() (*models.AgentMessage, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentMessage), nil
	}
}

func (a agentMessageDo) FindByPage(offset int, limit int) (result []*models.AgentMessage, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentMessageDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentMessageDo) Delete(models ...*models.AgentMessage) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentMessageDo) withDO(do gen.Dao) *agentMessageDo {
	a.DO = *do.(*gen.DO)
	return a
}
