// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newFileAsset(db *gorm.DB, opts ...gen.DOOption) fileAsset {
	_fileAsset := fileAsset{}

	_fileAsset.fileAssetDo.UseDB(db, opts...)
	_fileAsset.fileAssetDo.UseModel(&models.FileAsset{})

	tableName := _fileAsset.fileAssetDo.TableName()
	_fileAsset.ALL = field.NewAsterisk(tableName)
	_fileAsset.ID = field.NewUint64(tableName, "id")
	_fileAsset.CreatedAt = field.NewTime(tableName, "created_at")
	_fileAsset.UpdatedAt = field.NewTime(tableName, "updated_at")
	_fileAsset.CreatedBy = field.NewUint64(tableName, "created_by")
	_fileAsset.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_fileAsset.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_fileAsset.Remark = field.NewString(tableName, "remark")
	_fileAsset.DeletedAt = field.NewUint(tableName, "deleted_at")
	_fileAsset.Engine = field.NewString(tableName, "engine")
	_fileAsset.Bucket = field.NewString(tableName, "bucket")
	_fileAsset.ObjectKey = field.NewString(tableName, "object_key")
	_fileAsset.OriginalName = field.NewString(tableName, "original_name")
	_fileAsset.ContentType = field.NewString(tableName, "content_type")
	_fileAsset.Extension = field.NewString(tableName, "extension")
	_fileAsset.Size = field.NewInt64(tableName, "size")
	_fileAsset.SHA256 = field.NewString(tableName, "sha256")
	_fileAsset.BizType = field.NewString(tableName, "biz_type")
	_fileAsset.BizID = field.NewString(tableName, "biz_id")
	_fileAsset.Metadata = field.NewField(tableName, "metadata")
	_fileAsset.Status = field.NewString(tableName, "status")

	_fileAsset.fillFieldMap()

	return _fileAsset
}

type fileAsset struct {
	fileAssetDo

	ALL          field.Asterisk
	ID           field.Uint64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	CreatedBy    field.Uint64
	UpdatedBy    field.Uint64
	DeletedBy    field.Uint64
	Remark       field.String
	DeletedAt    field.Uint
	Engine       field.String // 存储引擎
	Bucket       field.String // bucket
	ObjectKey    field.String // 对象key
	OriginalName field.String // 原始文件名
	ContentType  field.String // 内容类型
	Extension    field.String // 文件扩展名
	Size         field.Int64  // 文件大小
	SHA256       field.String // SHA256
	BizType      field.String // 业务类型
	BizID        field.String // 业务ID
	Metadata     field.Field  // 扩展元数据
	Status       field.String // 状态

	fieldMap map[string]field.Expr
}

func (f fileAsset) Table(newTableName string) *fileAsset {
	f.fileAssetDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fileAsset) As(alias string) *fileAsset {
	f.fileAssetDo.DO = *(f.fileAssetDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fileAsset) updateTableName(table string) *fileAsset {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewUint64(table, "id")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.CreatedBy = field.NewUint64(table, "created_by")
	f.UpdatedBy = field.NewUint64(table, "updated_by")
	f.DeletedBy = field.NewUint64(table, "deleted_by")
	f.Remark = field.NewString(table, "remark")
	f.DeletedAt = field.NewUint(table, "deleted_at")
	f.Engine = field.NewString(table, "engine")
	f.Bucket = field.NewString(table, "bucket")
	f.ObjectKey = field.NewString(table, "object_key")
	f.OriginalName = field.NewString(table, "original_name")
	f.ContentType = field.NewString(table, "content_type")
	f.Extension = field.NewString(table, "extension")
	f.Size = field.NewInt64(table, "size")
	f.SHA256 = field.NewString(table, "sha256")
	f.BizType = field.NewString(table, "biz_type")
	f.BizID = field.NewString(table, "biz_id")
	f.Metadata = field.NewField(table, "metadata")
	f.Status = field.NewString(table, "status")

	f.fillFieldMap()

	return f
}

func (f *fileAsset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fileAsset) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 20)
	f.fieldMap["id"] = f.ID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["created_by"] = f.CreatedBy
	f.fieldMap["updated_by"] = f.UpdatedBy
	f.fieldMap["deleted_by"] = f.DeletedBy
	f.fieldMap["remark"] = f.Remark
	f.fieldMap["deleted_at"] = f.DeletedAt
	f.fieldMap["engine"] = f.Engine
	f.fieldMap["bucket"] = f.Bucket
	f.fieldMap["object_key"] = f.ObjectKey
	f.fieldMap["original_name"] = f.OriginalName
	f.fieldMap["content_type"] = f.ContentType
	f.fieldMap["extension"] = f.Extension
	f.fieldMap["size"] = f.Size
	f.fieldMap["sha256"] = f.SHA256
	f.fieldMap["biz_type"] = f.BizType
	f.fieldMap["biz_id"] = f.BizID
	f.fieldMap["metadata"] = f.Metadata
	f.fieldMap["status"] = f.Status
}

func (f fileAsset) clone(db *gorm.DB) fileAsset {
	f.fileAssetDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fileAsset) replaceDB(db *gorm.DB) fileAsset {
	f.fileAssetDo.ReplaceDB(db)
	return f
}

type fileAssetDo struct{ gen.DO }

type IFileAssetDo interface {
	gen.SubQuery
	Debug() IFileAssetDo
	WithContext(ctx context.Context) IFileAssetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileAssetDo
	WriteDB() IFileAssetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileAssetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileAssetDo
	Not(conds ...gen.Condition) IFileAssetDo
	Or(conds ...gen.Condition) IFileAssetDo
	Select(conds ...field.Expr) IFileAssetDo
	Where(conds ...gen.Condition) IFileAssetDo
	Order(conds ...field.Expr) IFileAssetDo
	Distinct(cols ...field.Expr) IFileAssetDo
	Omit(cols ...field.Expr) IFileAssetDo
	Join(table schema.Tabler, on ...field.Expr) IFileAssetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileAssetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileAssetDo
	Group(cols ...field.Expr) IFileAssetDo
	Having(conds ...gen.Condition) IFileAssetDo
	Limit(limit int) IFileAssetDo
	Offset(offset int) IFileAssetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileAssetDo
	Unscoped() IFileAssetDo
	Create(values ...*models.FileAsset) error
	CreateInBatches(values []*models.FileAsset, batchSize int) error
	Save(values ...*models.FileAsset) error
	First() (*models.FileAsset, error)
	Take() (*models.FileAsset, error)
	Last() (*models.FileAsset, error)
	Find() ([]*models.FileAsset, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FileAsset, err error)
	FindInBatches(result *[]*models.FileAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.FileAsset) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileAssetDo
	Assign(attrs ...field.AssignExpr) IFileAssetDo
	Joins(fields ...field.RelationField) IFileAssetDo
	Preload(fields ...field.RelationField) IFileAssetDo
	FirstOrInit() (*models.FileAsset, error)
	FirstOrCreate() (*models.FileAsset, error)
	FindByPage(offset int, limit int) (result []*models.FileAsset, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileAssetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileAssetDo) Debug() IFileAssetDo {
	return f.withDO(f.DO.Debug())
}

func (f fileAssetDo) WithContext(ctx context.Context) IFileAssetDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileAssetDo) ReadDB() IFileAssetDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileAssetDo) WriteDB() IFileAssetDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileAssetDo) Session(config *gorm.Session) IFileAssetDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileAssetDo) Clauses(conds ...clause.Expression) IFileAssetDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileAssetDo) Returning(value interface{}, columns ...string) IFileAssetDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileAssetDo) Not(conds ...gen.Condition) IFileAssetDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileAssetDo) Or(conds ...gen.Condition) IFileAssetDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileAssetDo) Select(conds ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileAssetDo) Where(conds ...gen.Condition) IFileAssetDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileAssetDo) Order(conds ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileAssetDo) Distinct(cols ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileAssetDo) Omit(cols ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileAssetDo) Join(table schema.Tabler, on ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileAssetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileAssetDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileAssetDo) Group(cols ...field.Expr) IFileAssetDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileAssetDo) Having(conds ...gen.Condition) IFileAssetDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileAssetDo) Limit(limit int) IFileAssetDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileAssetDo) Offset(offset int) IFileAssetDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileAssetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileAssetDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileAssetDo) Unscoped() IFileAssetDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileAssetDo) Create(values ...*models.FileAsset) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileAssetDo) CreateInBatches(values []*models.FileAsset, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileAssetDo) Save(values ...*models.FileAsset) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileAssetDo) First() (*models.FileAsset, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileAsset), nil
	}
}

func (f fileAssetDo) Take() (*models.FileAsset, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileAsset), nil
	}
}

func (f fileAssetDo) Last() (*models.FileAsset, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileAsset), nil
	}
}

func (f fileAssetDo) Find() ([]*models.FileAsset, error) {
	result, err := f.DO.Find()
	return result.([]*models.FileAsset), err
}

func (f fileAssetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FileAsset, err error) {
	buf := make([]*models.FileAsset, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileAssetDo) FindInBatches(result *[]*models.FileAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileAssetDo) Attrs(attrs ...field.AssignExpr) IFileAssetDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileAssetDo) Assign(attrs ...field.AssignExpr) IFileAssetDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileAssetDo) Joins(fields ...field.RelationField) IFileAssetDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileAssetDo) Preload(fields ...field.RelationField) IFileAssetDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileAssetDo) FirstOrInit() (*models.FileAsset, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileAsset), nil
	}
}

func (f fileAssetDo) FirstOrCreate() (*models.FileAsset, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileAsset), nil
	}
}

func (f fileAssetDo) FindByPage(offset int, limit int) (result []*models.FileAsset, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileAssetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileAssetDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileAssetDo) Delete(models ...*models.FileAsset) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileAssetDo) withDO(do gen.Dao) *fileAssetDo {
	f.DO = *do.(*gen.DO)
	return f
}
