// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newKnowledgeCollection(db *gorm.DB, opts ...gen.DOOption) knowledgeCollection {
	_knowledgeCollection := knowledgeCollection{}

	_knowledgeCollection.knowledgeCollectionDo.UseDB(db, opts...)
	_knowledgeCollection.knowledgeCollectionDo.UseModel(&models.KnowledgeCollection{})

	tableName := _knowledgeCollection.knowledgeCollectionDo.TableName()
	_knowledgeCollection.ALL = field.NewAsterisk(tableName)
	_knowledgeCollection.ID = field.NewUint64(tableName, "id")
	_knowledgeCollection.CreatedAt = field.NewTime(tableName, "created_at")
	_knowledgeCollection.UpdatedAt = field.NewTime(tableName, "updated_at")
	_knowledgeCollection.CreatedBy = field.NewUint64(tableName, "created_by")
	_knowledgeCollection.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_knowledgeCollection.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_knowledgeCollection.IsEnabled = field.NewBool(tableName, "is_enabled")
	_knowledgeCollection.Remark = field.NewString(tableName, "remark")
	_knowledgeCollection.DeletedAt = field.NewUint(tableName, "deleted_at")
	_knowledgeCollection.CollectionName = field.NewString(tableName, "collection_name")
	_knowledgeCollection.DisplayName = field.NewString(tableName, "display_name")
	_knowledgeCollection.MetricType = field.NewString(tableName, "metric_type")
	_knowledgeCollection.IndexType = field.NewString(tableName, "index_type")

	_knowledgeCollection.fillFieldMap()

	return _knowledgeCollection
}

type knowledgeCollection struct {
	knowledgeCollectionDo

	ALL              field.Asterisk
	ID               field.Uint64
	CreatedAt        field.Time
	UpdatedAt        field.Time
	CreatedBy        field.Uint64
	UpdatedBy        field.Uint64
	DeletedBy        field.Uint64
	IsEnabled        field.Bool
	Remark           field.String
	DeletedAt        field.Uint
	CollectionName   field.String // 集合名称（对应 Milvus Collection）
	DisplayName      field.String // 显示名称
	MetricType       field.String // 相似度度量类型
	IndexType        field.String // 索引类型

	fieldMap map[string]field.Expr
}

func (k knowledgeCollection) Table(newTableName string) *knowledgeCollection {
	k.knowledgeCollectionDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeCollection) As(alias string) *knowledgeCollection {
	k.knowledgeCollectionDo.DO = *(k.knowledgeCollectionDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeCollection) updateTableName(table string) *knowledgeCollection {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewUint64(table, "id")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")
	k.CreatedBy = field.NewUint64(table, "created_by")
	k.UpdatedBy = field.NewUint64(table, "updated_by")
	k.DeletedBy = field.NewUint64(table, "deleted_by")
	k.IsEnabled = field.NewBool(table, "is_enabled")
	k.Remark = field.NewString(table, "remark")
	k.DeletedAt = field.NewUint(table, "deleted_at")
	k.CollectionName = field.NewString(table, "collection_name")
	k.DisplayName = field.NewString(table, "display_name")
	k.MetricType = field.NewString(table, "metric_type")
	k.IndexType = field.NewString(table, "index_type")

	k.fillFieldMap()

	return k
}

func (k *knowledgeCollection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeCollection) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 13)
	k.fieldMap["id"] = k.ID
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
	k.fieldMap["created_by"] = k.CreatedBy
	k.fieldMap["updated_by"] = k.UpdatedBy
	k.fieldMap["deleted_by"] = k.DeletedBy
	k.fieldMap["is_enabled"] = k.IsEnabled
	k.fieldMap["remark"] = k.Remark
	k.fieldMap["deleted_at"] = k.DeletedAt
	k.fieldMap["collection_name"] = k.CollectionName
	k.fieldMap["display_name"] = k.DisplayName
	k.fieldMap["metric_type"] = k.MetricType
	k.fieldMap["index_type"] = k.IndexType
}

func (k knowledgeCollection) clone(db *gorm.DB) knowledgeCollection {
	k.knowledgeCollectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgeCollection) replaceDB(db *gorm.DB) knowledgeCollection {
	k.knowledgeCollectionDo.ReplaceDB(db)
	return k
}

type knowledgeCollectionDo struct{ gen.DO }

type IKnowledgeCollectionDo interface {
	gen.SubQuery
	Debug() IKnowledgeCollectionDo
	WithContext(ctx context.Context) IKnowledgeCollectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKnowledgeCollectionDo
	WriteDB() IKnowledgeCollectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKnowledgeCollectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKnowledgeCollectionDo
	Not(conds ...gen.Condition) IKnowledgeCollectionDo
	Or(conds ...gen.Condition) IKnowledgeCollectionDo
	Select(conds ...field.Expr) IKnowledgeCollectionDo
	Where(conds ...gen.Condition) IKnowledgeCollectionDo
	Order(conds ...field.Expr) IKnowledgeCollectionDo
	Distinct(cols ...field.Expr) IKnowledgeCollectionDo
	Omit(cols ...field.Expr) IKnowledgeCollectionDo
	Join(table schema.Tabler, on ...field.Expr) IKnowledgeCollectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCollectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCollectionDo
	Group(cols ...field.Expr) IKnowledgeCollectionDo
	Having(conds ...gen.Condition) IKnowledgeCollectionDo
	Limit(limit int) IKnowledgeCollectionDo
	Offset(offset int) IKnowledgeCollectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeCollectionDo
	Unscoped() IKnowledgeCollectionDo
	Create(values ...*models.KnowledgeCollection) error
	CreateInBatches(values []*models.KnowledgeCollection, batchSize int) error
	Save(values ...*models.KnowledgeCollection) error
	First() (*models.KnowledgeCollection, error)
	Take() (*models.KnowledgeCollection, error)
	Last() (*models.KnowledgeCollection, error)
	Find() ([]*models.KnowledgeCollection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.KnowledgeCollection, err error)
	FindInBatches(result *[]*models.KnowledgeCollection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.KnowledgeCollection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKnowledgeCollectionDo
	Assign(attrs ...field.AssignExpr) IKnowledgeCollectionDo
	Joins(fields ...field.RelationField) IKnowledgeCollectionDo
	Preload(fields ...field.RelationField) IKnowledgeCollectionDo
	FirstOrInit() (*models.KnowledgeCollection, error)
	FirstOrCreate() (*models.KnowledgeCollection, error)
	FindByPage(offset int, limit int) (result []*models.KnowledgeCollection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKnowledgeCollectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k knowledgeCollectionDo) Debug() IKnowledgeCollectionDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeCollectionDo) WithContext(ctx context.Context) IKnowledgeCollectionDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeCollectionDo) ReadDB() IKnowledgeCollectionDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeCollectionDo) WriteDB() IKnowledgeCollectionDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeCollectionDo) Session(config *gorm.Session) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeCollectionDo) Clauses(conds ...clause.Expression) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeCollectionDo) Returning(value interface{}, columns ...string) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeCollectionDo) Not(conds ...gen.Condition) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeCollectionDo) Or(conds ...gen.Condition) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeCollectionDo) Select(conds ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeCollectionDo) Where(conds ...gen.Condition) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeCollectionDo) Order(conds ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeCollectionDo) Distinct(cols ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeCollectionDo) Omit(cols ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeCollectionDo) Join(table schema.Tabler, on ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeCollectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeCollectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeCollectionDo) Group(cols ...field.Expr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeCollectionDo) Having(conds ...gen.Condition) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeCollectionDo) Limit(limit int) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeCollectionDo) Offset(offset int) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeCollectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeCollectionDo) Unscoped() IKnowledgeCollectionDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeCollectionDo) Create(values ...*models.KnowledgeCollection) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeCollectionDo) CreateInBatches(values []*models.KnowledgeCollection, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeCollectionDo) Save(values ...*models.KnowledgeCollection) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeCollectionDo) First() (*models.KnowledgeCollection, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeCollection), nil
	}
}

func (k knowledgeCollectionDo) Take() (*models.KnowledgeCollection, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeCollection), nil
	}
}

func (k knowledgeCollectionDo) Last() (*models.KnowledgeCollection, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeCollection), nil
	}
}

func (k knowledgeCollectionDo) Find() ([]*models.KnowledgeCollection, error) {
	result, err := k.DO.Find()
	return result.([]*models.KnowledgeCollection), err
}

func (k knowledgeCollectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.KnowledgeCollection, err error) {
	buf := make([]*models.KnowledgeCollection, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeCollectionDo) FindInBatches(result *[]*models.KnowledgeCollection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeCollectionDo) Attrs(attrs ...field.AssignExpr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeCollectionDo) Assign(attrs ...field.AssignExpr) IKnowledgeCollectionDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeCollectionDo) Joins(fields ...field.RelationField) IKnowledgeCollectionDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeCollectionDo) Preload(fields ...field.RelationField) IKnowledgeCollectionDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeCollectionDo) FirstOrInit() (*models.KnowledgeCollection, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeCollection), nil
	}
}

func (k knowledgeCollectionDo) FirstOrCreate() (*models.KnowledgeCollection, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeCollection), nil
	}
}

func (k knowledgeCollectionDo) FindByPage(offset int, limit int) (result []*models.KnowledgeCollection, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeCollectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeCollectionDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeCollectionDo) Delete(models ...*models.KnowledgeCollection) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeCollectionDo) withDO(do gen.Dao) *knowledgeCollectionDo {
	k.DO = *do.(*gen.DO)
	return k
}
