// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newKnowledgeDocument(db *gorm.DB, opts ...gen.DOOption) knowledgeDocument {
	_knowledgeDocument := knowledgeDocument{}

	_knowledgeDocument.knowledgeDocumentDo.UseDB(db, opts...)
	_knowledgeDocument.knowledgeDocumentDo.UseModel(&models.KnowledgeDocument{})

	tableName := _knowledgeDocument.knowledgeDocumentDo.TableName()
	_knowledgeDocument.ALL = field.NewAsterisk(tableName)
	_knowledgeDocument.ID = field.NewUint64(tableName, "id")
	_knowledgeDocument.CreatedAt = field.NewTime(tableName, "created_at")
	_knowledgeDocument.UpdatedAt = field.NewTime(tableName, "updated_at")
	_knowledgeDocument.CreatedBy = field.NewUint64(tableName, "created_by")
	_knowledgeDocument.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_knowledgeDocument.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_knowledgeDocument.IsEnabled = field.NewBool(tableName, "is_enabled")
	_knowledgeDocument.Remark = field.NewString(tableName, "remark")
	_knowledgeDocument.DeletedAt = field.NewUint(tableName, "deleted_at")
	_knowledgeDocument.CollectionID = field.NewUint64(tableName, "collection_id")
	_knowledgeDocument.DocumentID = field.NewString(tableName, "document_id")
	_knowledgeDocument.Title = field.NewString(tableName, "title")
	_knowledgeDocument.Content = field.NewString(tableName, "content")
	_knowledgeDocument.ContentType = field.NewString(tableName, "content_type")
	_knowledgeDocument.Source = field.NewString(tableName, "source")
	_knowledgeDocument.ChunkIndex = field.NewInt(tableName, "chunk_index")
	_knowledgeDocument.TotalChunks = field.NewInt(tableName, "total_chunks")
	_knowledgeDocument.VectorStatus = field.NewString(tableName, "vector_status")
	_knowledgeDocument.VectorID = field.NewString(tableName, "vector_id")
	_knowledgeDocument.Metadata = field.NewField(tableName, "metadata")
	_knowledgeDocument.IndexingError = field.NewString(tableName, "indexing_error")
	_knowledgeDocument.LastIndexedAt = field.NewInt64(tableName, "last_indexed_at")
	_knowledgeDocument.Collection = knowledgeDocumentBelongsToCollection{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Collection", "models.KnowledgeCollection"),
	}

	_knowledgeDocument.fillFieldMap()

	return _knowledgeDocument
}

type knowledgeDocument struct {
	knowledgeDocumentDo

	ALL           field.Asterisk
	ID            field.Uint64
	CreatedAt     field.Time
	UpdatedAt     field.Time
	CreatedBy     field.Uint64
	UpdatedBy     field.Uint64
	DeletedBy     field.Uint64
	IsEnabled     field.Bool
	Remark        field.String
	DeletedAt     field.Uint
	CollectionID  field.Uint64 // 所属集合ID
	DocumentID    field.String // 文档唯一标识（对应 Milvus ID）
	Title         field.String // 文档标题
	Content       field.String // 文档内容
	ContentType   field.String // 内容类型 text/markdown/pdf/html
	Source        field.String // 来源路径或URL
	ChunkIndex    field.Int    // 分块索引，同一文档的多块内容
	TotalChunks   field.Int    // 总分块数
	VectorStatus  field.String // 向量状态 pending/indexed/failed
	VectorID      field.String // Milvus 中的向量ID
	Metadata      field.Field  // 扩展元数据
	IndexingError field.String // 索引错误信息
	LastIndexedAt field.Int64  // 最后索引时间
	Collection    knowledgeDocumentBelongsToCollection

	fieldMap map[string]field.Expr
}

func (k knowledgeDocument) Table(newTableName string) *knowledgeDocument {
	k.knowledgeDocumentDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeDocument) As(alias string) *knowledgeDocument {
	k.knowledgeDocumentDo.DO = *(k.knowledgeDocumentDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeDocument) updateTableName(table string) *knowledgeDocument {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewUint64(table, "id")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")
	k.CreatedBy = field.NewUint64(table, "created_by")
	k.UpdatedBy = field.NewUint64(table, "updated_by")
	k.DeletedBy = field.NewUint64(table, "deleted_by")
	k.IsEnabled = field.NewBool(table, "is_enabled")
	k.Remark = field.NewString(table, "remark")
	k.DeletedAt = field.NewUint(table, "deleted_at")
	k.CollectionID = field.NewUint64(table, "collection_id")
	k.DocumentID = field.NewString(table, "document_id")
	k.Title = field.NewString(table, "title")
	k.Content = field.NewString(table, "content")
	k.ContentType = field.NewString(table, "content_type")
	k.Source = field.NewString(table, "source")
	k.ChunkIndex = field.NewInt(table, "chunk_index")
	k.TotalChunks = field.NewInt(table, "total_chunks")
	k.VectorStatus = field.NewString(table, "vector_status")
	k.VectorID = field.NewString(table, "vector_id")
	k.Metadata = field.NewField(table, "metadata")
	k.IndexingError = field.NewString(table, "indexing_error")
	k.LastIndexedAt = field.NewInt64(table, "last_indexed_at")

	k.fillFieldMap()

	return k
}

func (k *knowledgeDocument) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeDocument) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 23)
	k.fieldMap["id"] = k.ID
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
	k.fieldMap["created_by"] = k.CreatedBy
	k.fieldMap["updated_by"] = k.UpdatedBy
	k.fieldMap["deleted_by"] = k.DeletedBy
	k.fieldMap["is_enabled"] = k.IsEnabled
	k.fieldMap["remark"] = k.Remark
	k.fieldMap["deleted_at"] = k.DeletedAt
	k.fieldMap["collection_id"] = k.CollectionID
	k.fieldMap["document_id"] = k.DocumentID
	k.fieldMap["title"] = k.Title
	k.fieldMap["content"] = k.Content
	k.fieldMap["content_type"] = k.ContentType
	k.fieldMap["source"] = k.Source
	k.fieldMap["chunk_index"] = k.ChunkIndex
	k.fieldMap["total_chunks"] = k.TotalChunks
	k.fieldMap["vector_status"] = k.VectorStatus
	k.fieldMap["vector_id"] = k.VectorID
	k.fieldMap["metadata"] = k.Metadata
	k.fieldMap["indexing_error"] = k.IndexingError
	k.fieldMap["last_indexed_at"] = k.LastIndexedAt

}

func (k knowledgeDocument) clone(db *gorm.DB) knowledgeDocument {
	k.knowledgeDocumentDo.ReplaceConnPool(db.Statement.ConnPool)
	k.Collection.db = db.Session(&gorm.Session{Initialized: true})
	k.Collection.db.Statement.ConnPool = db.Statement.ConnPool
	return k
}

func (k knowledgeDocument) replaceDB(db *gorm.DB) knowledgeDocument {
	k.knowledgeDocumentDo.ReplaceDB(db)
	k.Collection.db = db.Session(&gorm.Session{})
	return k
}

type knowledgeDocumentBelongsToCollection struct {
	db *gorm.DB

	field.RelationField
}

func (a knowledgeDocumentBelongsToCollection) Where(conds ...field.Expr) *knowledgeDocumentBelongsToCollection {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a knowledgeDocumentBelongsToCollection) WithContext(ctx context.Context) *knowledgeDocumentBelongsToCollection {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a knowledgeDocumentBelongsToCollection) Session(session *gorm.Session) *knowledgeDocumentBelongsToCollection {
	a.db = a.db.Session(session)
	return &a
}

func (a knowledgeDocumentBelongsToCollection) Model(m *models.KnowledgeDocument) *knowledgeDocumentBelongsToCollectionTx {
	return &knowledgeDocumentBelongsToCollectionTx{a.db.Model(m).Association(a.Name())}
}

func (a knowledgeDocumentBelongsToCollection) Unscoped() *knowledgeDocumentBelongsToCollection {
	a.db = a.db.Unscoped()
	return &a
}

type knowledgeDocumentBelongsToCollectionTx struct{ tx *gorm.Association }

func (a knowledgeDocumentBelongsToCollectionTx) Find() (result *models.KnowledgeCollection, err error) {
	return result, a.tx.Find(&result)
}

func (a knowledgeDocumentBelongsToCollectionTx) Append(values ...*models.KnowledgeCollection) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a knowledgeDocumentBelongsToCollectionTx) Replace(values ...*models.KnowledgeCollection) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a knowledgeDocumentBelongsToCollectionTx) Delete(values ...*models.KnowledgeCollection) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a knowledgeDocumentBelongsToCollectionTx) Clear() error {
	return a.tx.Clear()
}

func (a knowledgeDocumentBelongsToCollectionTx) Count() int64 {
	return a.tx.Count()
}

func (a knowledgeDocumentBelongsToCollectionTx) Unscoped() *knowledgeDocumentBelongsToCollectionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type knowledgeDocumentDo struct{ gen.DO }

type IKnowledgeDocumentDo interface {
	gen.SubQuery
	Debug() IKnowledgeDocumentDo
	WithContext(ctx context.Context) IKnowledgeDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKnowledgeDocumentDo
	WriteDB() IKnowledgeDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKnowledgeDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKnowledgeDocumentDo
	Not(conds ...gen.Condition) IKnowledgeDocumentDo
	Or(conds ...gen.Condition) IKnowledgeDocumentDo
	Select(conds ...field.Expr) IKnowledgeDocumentDo
	Where(conds ...gen.Condition) IKnowledgeDocumentDo
	Order(conds ...field.Expr) IKnowledgeDocumentDo
	Distinct(cols ...field.Expr) IKnowledgeDocumentDo
	Omit(cols ...field.Expr) IKnowledgeDocumentDo
	Join(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo
	Group(cols ...field.Expr) IKnowledgeDocumentDo
	Having(conds ...gen.Condition) IKnowledgeDocumentDo
	Limit(limit int) IKnowledgeDocumentDo
	Offset(offset int) IKnowledgeDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeDocumentDo
	Unscoped() IKnowledgeDocumentDo
	Create(values ...*models.KnowledgeDocument) error
	CreateInBatches(values []*models.KnowledgeDocument, batchSize int) error
	Save(values ...*models.KnowledgeDocument) error
	First() (*models.KnowledgeDocument, error)
	Take() (*models.KnowledgeDocument, error)
	Last() (*models.KnowledgeDocument, error)
	Find() ([]*models.KnowledgeDocument, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.KnowledgeDocument, err error)
	FindInBatches(result *[]*models.KnowledgeDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.KnowledgeDocument) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKnowledgeDocumentDo
	Assign(attrs ...field.AssignExpr) IKnowledgeDocumentDo
	Joins(fields ...field.RelationField) IKnowledgeDocumentDo
	Preload(fields ...field.RelationField) IKnowledgeDocumentDo
	FirstOrInit() (*models.KnowledgeDocument, error)
	FirstOrCreate() (*models.KnowledgeDocument, error)
	FindByPage(offset int, limit int) (result []*models.KnowledgeDocument, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKnowledgeDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k knowledgeDocumentDo) Debug() IKnowledgeDocumentDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeDocumentDo) WithContext(ctx context.Context) IKnowledgeDocumentDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeDocumentDo) ReadDB() IKnowledgeDocumentDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeDocumentDo) WriteDB() IKnowledgeDocumentDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeDocumentDo) Session(config *gorm.Session) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeDocumentDo) Clauses(conds ...clause.Expression) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeDocumentDo) Returning(value interface{}, columns ...string) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeDocumentDo) Not(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeDocumentDo) Or(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeDocumentDo) Select(conds ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeDocumentDo) Where(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeDocumentDo) Order(conds ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeDocumentDo) Distinct(cols ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeDocumentDo) Omit(cols ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeDocumentDo) Join(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeDocumentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeDocumentDo) RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeDocumentDo) Group(cols ...field.Expr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeDocumentDo) Having(conds ...gen.Condition) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeDocumentDo) Limit(limit int) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeDocumentDo) Offset(offset int) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeDocumentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeDocumentDo) Unscoped() IKnowledgeDocumentDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeDocumentDo) Create(values ...*models.KnowledgeDocument) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeDocumentDo) CreateInBatches(values []*models.KnowledgeDocument, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeDocumentDo) Save(values ...*models.KnowledgeDocument) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeDocumentDo) First() (*models.KnowledgeDocument, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) Take() (*models.KnowledgeDocument, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) Last() (*models.KnowledgeDocument, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) Find() ([]*models.KnowledgeDocument, error) {
	result, err := k.DO.Find()
	return result.([]*models.KnowledgeDocument), err
}

func (k knowledgeDocumentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.KnowledgeDocument, err error) {
	buf := make([]*models.KnowledgeDocument, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeDocumentDo) FindInBatches(result *[]*models.KnowledgeDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeDocumentDo) Attrs(attrs ...field.AssignExpr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeDocumentDo) Assign(attrs ...field.AssignExpr) IKnowledgeDocumentDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeDocumentDo) Joins(fields ...field.RelationField) IKnowledgeDocumentDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeDocumentDo) Preload(fields ...field.RelationField) IKnowledgeDocumentDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeDocumentDo) FirstOrInit() (*models.KnowledgeDocument, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) FirstOrCreate() (*models.KnowledgeDocument, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.KnowledgeDocument), nil
	}
}

func (k knowledgeDocumentDo) FindByPage(offset int, limit int) (result []*models.KnowledgeDocument, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeDocumentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeDocumentDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeDocumentDo) Delete(models ...*models.KnowledgeDocument) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeDocumentDo) withDO(do gen.Dao) *knowledgeDocumentDo {
	k.DO = *do.(*gen.DO)
	return k
}
