// Code generated by MockGen. DO NOT EDIT.
// Source: file_storage.go
//
// Generated by this command:
//
//	mockgen -source=file_storage.go -destination=../mock/mock_file_storage.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	appsvc "admin/internal/appsvc"
	models "admin/internal/services/orm/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileStorage) Delete(ctx context.Context, id, operatorID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, operatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStorageMockRecorder) Delete(ctx, id, operatorID any) *MockFileStorageDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStorage)(nil).Delete), ctx, id, operatorID)
	return &MockFileStorageDeleteCall{Call: call}
}

// MockFileStorageDeleteCall wrap *gomock.Call
type MockFileStorageDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileStorageDeleteCall) Return(arg0 error) *MockFileStorageDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileStorageDeleteCall) Do(f func(context.Context, uint64, uint64) error) *MockFileStorageDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileStorageDeleteCall) DoAndReturn(f func(context.Context, uint64, uint64) error) *MockFileStorageDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Detail mocks base method.
func (m *MockFileStorage) Detail(ctx context.Context, id uint64) (*models.FileAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(*models.FileAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockFileStorageMockRecorder) Detail(ctx, id any) *MockFileStorageDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockFileStorage)(nil).Detail), ctx, id)
	return &MockFileStorageDetailCall{Call: call}
}

// MockFileStorageDetailCall wrap *gomock.Call
type MockFileStorageDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileStorageDetailCall) Return(arg0 *models.FileAsset, arg1 error) *MockFileStorageDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileStorageDetailCall) Do(f func(context.Context, uint64) (*models.FileAsset, error)) *MockFileStorageDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileStorageDetailCall) DoAndReturn(f func(context.Context, uint64) (*models.FileAsset, error)) *MockFileStorageDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PresignedURL mocks base method.
func (m *MockFileStorage) PresignedURL(ctx context.Context, input appsvc.PresignedURLInput) (*appsvc.PresignedURLResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedURL", ctx, input)
	ret0, _ := ret[0].(*appsvc.PresignedURLResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedURL indicates an expected call of PresignedURL.
func (mr *MockFileStorageMockRecorder) PresignedURL(ctx, input any) *MockFileStoragePresignedURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedURL", reflect.TypeOf((*MockFileStorage)(nil).PresignedURL), ctx, input)
	return &MockFileStoragePresignedURLCall{Call: call}
}

// MockFileStoragePresignedURLCall wrap *gomock.Call
type MockFileStoragePresignedURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileStoragePresignedURLCall) Return(arg0 *appsvc.PresignedURLResult, arg1 error) *MockFileStoragePresignedURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileStoragePresignedURLCall) Do(f func(context.Context, appsvc.PresignedURLInput) (*appsvc.PresignedURLResult, error)) *MockFileStoragePresignedURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileStoragePresignedURLCall) DoAndReturn(f func(context.Context, appsvc.PresignedURLInput) (*appsvc.PresignedURLResult, error)) *MockFileStoragePresignedURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Upload mocks base method.
func (m *MockFileStorage) Upload(ctx context.Context, input appsvc.UploadInput) (*models.FileAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, input)
	ret0, _ := ret[0].(*models.FileAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileStorageMockRecorder) Upload(ctx, input any) *MockFileStorageUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileStorage)(nil).Upload), ctx, input)
	return &MockFileStorageUploadCall{Call: call}
}

// MockFileStorageUploadCall wrap *gomock.Call
type MockFileStorageUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileStorageUploadCall) Return(arg0 *models.FileAsset, arg1 error) *MockFileStorageUploadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileStorageUploadCall) Do(f func(context.Context, appsvc.UploadInput) (*models.FileAsset, error)) *MockFileStorageUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileStorageUploadCall) DoAndReturn(f func(context.Context, appsvc.UploadInput) (*models.FileAsset, error)) *MockFileStorageUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
